### PR TITLE
Added config to CCXT feed parameters

### PR DESCRIPTION
**Pull request by rmihael**
It's worth adding the config parameter to the feed class as well. Otherwise when trying to use sandbox broker is instantiated with a proper endpoint and feed still uses real environment.

---
This change is [Reviewable](https://reviewable.io/reviews/bartosh/backtrader/3)

### CODE REVIEW

**Comment by bartosh** [comment]
What's the point of using sandbox for public API? From my point of view it only makes sense to do for private/broker API, no?

**Comment by rmihael** [comment]
It makes sense for backtesting validation. In one run I want to run my strategy against sandbox (both feed and orders) and in another run -- against BackBroker with historical data strictly matching previous sandboxed run.
In that case, I would expect simulation results to be close to sandbox results. If that not true, then something is wrong with my backtesting and I should revisit it.

**Comment by bartosh** [comment]
Thanks for the explanations. That makes sense to me now.

Can we make this parameter optional?

**Comment by rmihael** [comment]
Sure, why not. I'll update PR.

**Comment by bartosh** [comment]
closed by cb921c2

**Pull request closed without merging**
