### PR TITLE
Fix for hasFetchOHLCV tag, so we work correctly with exchanges like Kraken that use the newer format

### PR DESCRIPTION
**Pull request by moogman**
As title; Tested OK against Kraken and Binance.

### CODE REVIEW

**Review by bartosh — CHANGES_REQUESTED** [review]
This approach doesn't work for bitmex:
In [1]: import ccxt

In [2]: exchange = ccxt.bitmex()

In [3]: exchange.has['fetchOHLCV']
Out[3]: False

In [4]: exchange.hasFetchOHLCV
Out[4]: True

We need to come up with something that works for all exchanges.

**Comment by bartosh** [comment]
BTW, I can't reproduce the issue with kraken:
In [5]: exchange = ccxt.kraken()

In [6]: exchange.hasFetchOHLCV
Out[6]: True

In [7]: exchange.has['fetchOHLCV']
Out[7]: True

**Comment by moogman** [comment]
Are you testing against a latest ccxt? I pulled from git just a few days ago, and saw the behaviour. I'll pop a change in to cover for both cases, as I'm sure it will bite others with and without this fix as-is

**Comment by bartosh** [comment]
Good point. This is what I've got with the latest ccxt master:
```
In [1]: import ccxt

In [2]: exchange = ccxt.kraken()

In [3]: exchange.hasFetchOHLCV
Out[3]: False

In [4]: exchange.has['fetchOHLCV']
Out[4]: True

In [5]: exchange = ccxt.bitmex()

In [6]: exchange.hasFetchOHLCV
Out[6]: False

In [7]: exchange.has['fetchOHLCV']
Out[7]: True
```

I'm just wondering would it be better to fix this in ccxt?
hasFetchOHLCV seems to be a standard method of checking this capability. Unlike has['fetchOHLCV'] it's mentioned in the ccxt manual.

**Comment by bartosh** [comment]
Looking at their commit log I'd say they're changing interface to has[<key>] approach. However, this is not the reason to break old interface. How about creating bug in their issue tracker or at least looking if similar bug exists?

**Review by bartosh — APPROVED** [review]
approving as it looks like they're not going to fix it in ccxt.

**Comment by bartosh** [comment]
merged into ccxt branch

**Pull request closed without merging**
