### PR TITLE
Bug fix concering live feed

### PR DESCRIPTION
**Pull request by FiV0**
I tried to fix the issue raised here
(https://community.backtrader.com/topic/623/anyone-use-backtrader-to-do-live-trading-on-bitcoin-exchange/199).
Mainly, the code got the ohlcv data of the current period, before it
had completely finished, meaning trades where missing. Currently the
code assumes that the timestamp is from the beginning of the
candleperiod, which is not always the case, but this is a ccxt issue and
I raised it here (https://github.com/ccxt/ccxt/issues/2206).

### CODE REVIEW

**Comment by FiV0** [comment]
I think it is best to put this on hold. First there is the issue with ccxt which I referenced above. So for example with the current version and `bitmex` people would get the lastest finished candle only one candleperiod later. 

Second, I realized that with this commit the live feed brakes if you have more then 1 feed with different compressions. This [gist](https://gist.github.com/FiV0/6ea2b37e39364943f0f095cab16da4f4) illustrates the issue (with this commit). So if for example one feed is `1m` data and another `5m` the `next()` method gets called twice at for example `16:40`. 
```
***** NEXT data0: 2018-03-11 16:38:00  9230.0 9240.0 9219.39 9231.0 31.286654 Minute 11
***** NEXT data1: 2018-03-11 16:30:00  9212.01 9245.83 9207.03 9215.13 121.879263 Minute 1
------ next len 12 - counter 11
***** NEXT data0: 2018-03-11 16:38:00  9230.0 9240.0 9219.39 9231.0 31.286654 Minute 11
***** NEXT data1: 2018-03-11 16:35:00  9224.98 9247.0 9192.8 9243.49 126.200746 Minute 2
------ next len 13 - counter 12
***** NEXT data0: 2018-03-11 16:39:00  9224.09 9247.0 9224.09 9243.49 22.682661 Minute 12
***** NEXT data1: 2018-03-11 16:35:00  9224.98 9247.0 9192.8 9243.49 126.200746 Minute 2
```

The `1m` candle 16:39-16:40 has finished and the `5m` candle 16:35-16:30 has finished, but their timestamps are misaligned and therefore apparently the `next()` method get called twice. So for backtrader it would be better if the ending time of a candle is used as time stamp.

So let me know if you want to wait until the `ccxt` issue has been resolved or they have at least found some standard or if you want me to continue on this. For the later one we would need to make some decisions based on the exchange  that is in use.

**Comment by bartosh** [comment]
I'd wait for ccxt fix. I don't think we should make workarounds in the feed code. The code is using ohlv data coming from ccxt as it is. Modifying it just because of ccxt bugs doesn't look right to me.

**Comment by bartosh** [comment]
This PR contains 22 commits for some reason. Can you rebase it on top of ccxt branch, please?

**Comment by FiV0** [comment]
The [ccxt issue](https://github.com/ccxt/ccxt/issues/2206) has been fixed if you want to go ahead merge this PR. I also added an partial option for the feed if people want to keep it the old way.

**Comment by FiV0** [comment]
Sorry to post this here as it is only partially related, but there is no issue tracker for forked repos. If you want me to post it in the future on the backtrader forum let me know.
So for example if I feed the following (also with your current verison) the `next()` mehthod never gets called.
```python
data1 = bt.feeds.CCXT(exchange=exchange, symbol=symbol,
                          timeframe=bt.TimeFrame.Minutes,
                          compression=1,
                          fromdate=datetime.utcnow(),
                          ohlcv_limit=99999)
cerebro.adddata(data1, name=symbol)
```
As the fromdate is "now" there is no historical data. I know this is a bit hypothetical, but the same issue should arise if one feeds `1h` data and sets `fromdate` to `datetime.utcnow() - timedelta(minutes=30)`. One I add one historical candle with `datetime.utcnow() - timedelta(minutes=1)`, everything is fine. I tried to understand the code but having trouble with [this](https://github.com/bartosh/backtrader/blob/ccxt/backtrader/feeds/ccxt.py#L93-L106) part. After some ugly `print` statements I figured that with the above example we never end up in the if of that part, meaning L96, which is apparently crucial for candles to be past to bt. Could you also explain why you have [this](https://github.com/bartosh/backtrader/blob/ccxt/backtrader/feeds/ccxt.py#L135) particular break condition. Could you just explain the two code parts I reference or fix the issue, maybe then I understand.

**Comment by rfanjul** [comment]
Hello. Would be that branch merged in some point? Would be possible to help here?

**Comment by bart0sh** [comment]
This branch has 23 commits and conflicts. I'm not sure it makes any sense to merge it.

BTW, which functionality are you intersted in?

**Comment by rfanjul** [comment]
I am testing ccxt, I'm following this thread https://community.backtrader.com/topic/623/anyone-use-backtrader-to-do-live-trading-on-bitcoin-exchange/242?page=13 , the main point for me is trade with cryptos but have also the backtesting. Thanks!

**Comment by bart0sh** [comment]
>  the main point for me is trade with cryptos but have also the backtesting.

This is understandable. I was asking about functionality from this PR. Which functionality from this PR are you interested in?

**Comment by rfanjul** [comment]
I would need Broker which is doing something strange asking for get_value and get_cash all the time, maybe it could be cached and when an order gets executed update the value again ( I got banned from bitfinex ) and ccxt._fetch_ohlcv with ccxtstore.get_granularity 

So basically open, close, get orders and timeframes with 15m, 1h,...

**Comment by bartosh** [comment]
closing. this PR conflicts with the target branch and not active for a long time.

**Pull request closed without merging**
