### PR TITLE
Moved CCXTOrder class and fix cancel method.

### PR DESCRIPTION
**Pull request by JaCoderX**

### CODE REVIEW

**Review by bartosh — APPROVED** [review]
Thank you! Approving & merging.

**Comment by kikingalgo** [comment]
Hi,

i get the below error when executing an order - after the latest merge

regards

 ```
File "/anaconda3/lib/python3.6/site-packages/backtrader/brokers/ccxtbroker.py", line 86, in buy
    return self._submit(owner, data, exectype, 'buy', size, price, kwargs)
  File "/anaconda3/lib/python3.6/site-packages/backtrader/brokers/ccxtbroker.py", line 78, in _submit
    order = CCXTOrder(owner, data, _order)
  File "/anaconda3/lib/python3.6/site-packages/backtrader/metabase.py", line 88, in __call__
    _obj, args, kwargs = cls.doinit(_obj, *args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/backtrader/metabase.py", line 78, in doinit
    _obj.__init__(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/backtrader/stores/ccxtstore.py", line 39, in __init__
    self.size = float(ccxt_order['info']['original_amount'])
KeyError: 'original_amount'

```

**Comment by bartosh** [comment]
which ccxt version do you use? Here you can see my setup (backtrader and ccxt versions): https://community.backtrader.com/post/6218

**Comment by jeffneuen** [comment]
I too am getting the same keyerror message. Version 1.17.88 of ccxt, and the latest version of this branch of backtrader as of today. Have hunted around but have not yet been able to figure out where the "original_amount" key is supposed to be set... I'm thinking it's something that's supposed to be pulled over from ccxt config, but I haven't found it yet. Did OP ever find a resolution?

**Comment by bartosh** [comment]
I think it's caused by this commit: https://github.com/bartosh/backtrader/commit/ae70f493ea0a148421ab4e4978632c798f388b63

Can you check if it works for you if you change line 34 of ccxtbroker.py to this?
```self.size = float(ccxt_order['info']['amount'])```

**Comment by jeffneuen** [comment]
Sure. Unless I'm missing something, the line to change would be like 39 in ccxtstore.py on the most recent version? I tried changing it, but I now get a keyerror for 'amount' on that line.

**Comment by jeffneuen** [comment]
Did a little more digging through the debug logs... It appears that a market order to open works, but the keyerror on amount is still occurring on the market order to close. Haven't been able to get a fix working though yet.

**Comment by jeffneuen** [comment]
fwiw, when I changed the line to: 

`self.size = float(ccxt_order['amount'])`

it seemed to work ok.

**Comment by kikingalgo** [comment]
works for me as well !
self.size = float(ccxt_order['amount'])

**Comment by bartosh** [comment]
It doesn't work for me with binance exchange:
```
    self.size = float(ccxt_order['amount'])
KeyError: 'amount'
```
 However, it works with self.size = float(ccxt_order['info']['original_amount'])

**Comment by bartosh** [comment]
sorry, it was with gemini exchange. Here is how order looks like there:

```
{'info': {'order_id': '103260747', 'id': '103260747', 'symbol': 'ethbtc', 'exchange': 'gemini', 'avg_execution_price': '0', 'side': 'buy', 'type': 'exchange limit', 'timestamp': '1533838231', 'timestampms': 1533838231619, 'is_live': False, 'is_cancelled': True, 'is_hidden': False, 'was_forced': False, 'executed_amount': '0', 'remaining_amount': '0.1', 'client_order_id': '1533838228638', 'reason': 'SelfCrossPrevented', 'options': [], 'price': '6000', 'original_amount': '0.1'}, 'id': '103260747'}
```

**Comment by bartosh** [comment]
Can you check if this works for you?

```
diff --git a/backtrader/stores/ccxtstore.py b/backtrader/stores/ccxtstore.py
index 673e9ee..4fb9c92 100644
--- a/backtrader/stores/ccxtstore.py
+++ b/backtrader/stores/ccxtstore.py
@@ -36,7 +36,11 @@ class CCXTOrder(OrderBase):
         self.data = data
         self.ccxt_order = ccxt_order
         self.ordtype = self.Buy if ccxt_order['info']['side'] == 'buy' else self.Sell
-        self.size = float(ccxt_order['info']['original_amount'])
+
+        size = ccxt_order.get('amount')
+        if size is None:
+            size = ccxt_order['info']['original_amount']
+        self.size = float(size)
 
         super(CCXTOrder, self).__init__()
```

**Comment by bartosh** [comment]
I think this would be better fix:

```
diff --git a/backtrader/stores/ccxtstore.py b/backtrader/stores/ccxtstore.py
index 673e9ee..962d8ba 100644
--- a/backtrader/stores/ccxtstore.py
+++ b/backtrader/stores/ccxtstore.py
@@ -35,8 +35,8 @@ class CCXTOrder(OrderBase):
         self.owner = owner
         self.data = data
         self.ccxt_order = ccxt_order
-        self.ordtype = self.Buy if ccxt_order['info']['side'] == 'buy' else self.Sell
-        self.size = float(ccxt_order['info']['original_amount'])
+        self.ordtype = self.Buy if ccxt_order['side'] == 'buy' else self.Sell
+        self.size = float(ccxt_order['amount'])
 
         super(CCXTOrder, self).__init__()
 
@@ -115,8 +115,9 @@ class CCXTStore(object):
 
     @retry
     def create_order(self, symbol, order_type, side, amount, price, params):
-        return self.exchange.create_order(symbol=symbol, type=order_type, side=side,
-                                          amount=amount, price=price, params=params)
+        order = self.exchange.create_order(symbol=symbol, type=order_type, side=side,
+                                           amount=amount, price=price, params=params)
+        return self.exchange.parse_order(order['info'])
 
     @retry
     def cancel_order(self, order):
```

Can you please check if it works for you?

**Comment by kikingalgo** [comment]
@bartosh 

when it comes to bitmex - this is the structure - if we parse back only order[info] we lose the other part - wouldn't we?

{'info': {'orderID': 'XYZ', 'clOrdID': '', 'clOrdLinkID': '', 'account': 111111, 'symbol': 'XBTUSD', 'side': 'Sell', 'simpleOrderQty': None, 'orderQty': 10, 'price': 7598, 'displayQty': None, 'stopPx'
: None, 'pegOffsetValue': None, 'pegPriceType': '', 'currency': 'USD', 'settlCurrency': 'XBt', 'ordType': 'Market', 'timeInForce': 'ImmediateOrCancel', 'execInst': '', 'contingencyType': '', 'exDestination': 'XBME', 'ordStatus': 'Fil
led', 'triggered': '', 'workingIndicator': False, 'ordRejReason': '', 'simpleLeavesQty': 0, 'leavesQty': 0, 'simpleCumQty': 0.0013161, 'cumQty': 10, 'avgPx': 7598, 'multiLegReportingType': 'SingleSecurity', 'text': 'Submitted via API
.', 'transactTime': '2018-08-01T14:32:57.365Z', 'timestamp': '2018-08-01T14:32:57.365Z'}, **'id': 'XYZ', 'timestamp': 1533133977365, 'datetime': '2018-08-01T14:32:57.365Z', 'lastTradeTimestamp': None, '
symbol': 'BTC/USD', 'type': 'market', 'side': 'sell', 'price': 7598.0, 'amount': 10.0, 'cost': 75980.0, 'filled': 10.0, 'remaining': 0.0, 'status': 'closed', 'fee': None}**

**Pull request merged**
